import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { get, set } from 'idb-keyval';

// Automatically precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Clean up old caches
cleanupOutdatedCaches();

// Take control of all pages immediately
self.skipWaiting();
clientsClaim();

// Handle Push Notifications
self.addEventListener('push', (event) => {
    let data = {};
    if (event.data) {
        try {
            data = event.data.json();
        } catch (e) {
            data = { body: event.data.text() };
        }
    }

    const title = data.title || 'New Message';
    const options = {
        body: data.body || 'You received a new message',
        icon: data.icon || '/pwa-192x192.png',
        badge: '/masked-icon.svg',
        data: data.url || '/',
        vibrate: [200, 100, 200],
    };

    event.waitUntil(
        self.registration.showNotification(title, options)
    );
});

// Handle Notification Clicks (Deep linking)
self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    const urlToOpen = event.notification.data;

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Check if there is already a window/tab open with the target URL
            let matchingClient = null;
            for (let i = 0; i < windowClients.length; i++) {
                const windowClient = windowClients[i];
                if (windowClient.url.includes(urlToOpen)) {
                    matchingClient = windowClient;
                    break;
                }
            }

            if (matchingClient) {
                // If open, focus it
                return matchingClient.focus();
            } else {
                // Otherwise open a new window/tab
                return clients.openWindow(urlToOpen);
            }
        })
    );
});

// Background Sync for Offline Drafts (Phase 7)
self.addEventListener('sync', (event) => {
    if (event.tag === 'sync-messages') {
        console.log('Background sync triggered for messages');
        event.waitUntil(
            (async () => {
                const queue = await get('offline_message_queue') || [];
                if (queue.length === 0) return;

                const failedQueue = [];

                for (const draft of queue) {
                    try {
                        const res = await fetch(draft.url, {
                            method: draft.method,
                            headers: draft.headers,
                            body: draft.body,
                        });

                        if (!res.ok) {
                            console.error('Failed to sync message', draft);
                            failedQueue.push(draft); // retry later
                        } else {
                            console.log('Successfully synced message', draft);
                            // Notify clients that the message was sent so they can refresh
                            const clientsList = await clients.matchAll({ type: 'window', includeUncontrolled: true });
                            clientsList.forEach(client => {
                                client.postMessage({
                                    type: 'MESSAGE_SYNC_SUCCESS',
                                    clientMessageId: draft.clientMessageId,
                                    conversationId: draft.conversationId
                                });
                            });
                        }
                    } catch (err) {
                        console.error('Network error during sync', err);
                        failedQueue.push(draft);
                    }
                }

                // Update the queue with any that failed
                await set('offline_message_queue', failedQueue);
            })()
        );
    }
});
